"""
SuperWork Data Models

All shared types for the SuperWork supervisor platform layer.
Imports RiskLevel from core but otherwise has no framework dependencies.
"""

import uuid
from datetime import UTC, datetime
from enum import StrEnum

from pydantic import BaseModel, Field

from kovrin.core.models import RiskLevel

# ─── Enums ───────────────────────────────────────────────────


class SessionStatus(StrEnum):
    """Status of a SuperWork supervisor session."""

    INITIALIZING = "INITIALIZING"
    WATCHING = "WATCHING"
    PAUSED = "PAUSED"
    STOPPED = "STOPPED"


class ProposalStatus(StrEnum):
    """Lifecycle of a task proposal from the Orchestrator."""

    PENDING = "PENDING"
    APPROVED = "APPROVED"
    SKIPPED = "SKIPPED"
    EXECUTING = "EXECUTING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


# ─── Event Models ────────────────────────────────────────────


class TaskCompletionEvent(BaseModel):
    """Event emitted by Session Watcher when a task completes.

    Parsed from Claude Code JSONL session files. Contains
    summary information about what was accomplished.
    """

    id: str = Field(default_factory=lambda: f"tce-{uuid.uuid4().hex[:8]}")
    session_id: str = ""
    project_path: str = ""
    completed_task: str = ""
    output_summary: str = ""
    files_changed: list[str] = Field(default_factory=list)
    errors: list[str] = Field(default_factory=list)
    duration_seconds: int = 0
    timestamp: datetime = Field(default_factory=lambda: datetime.now(UTC))


# ─── Proposal Models ────────────────────────────────────────


class TaskProposal(BaseModel):
    """A proposed task generated by the Orchestrator Agent.

    Contains everything needed for a human to decide whether
    to approve or skip the task.
    """

    id: str = Field(default_factory=lambda: f"prop-{uuid.uuid4().hex[:8]}")
    title: str
    description: str
    rationale: str = ""
    risk_level: RiskLevel = RiskLevel.LOW
    estimated_tokens: int = 0
    auto_execute: bool = False
    dependencies: list[str] = Field(default_factory=list)
    status: ProposalStatus = ProposalStatus.PENDING
    priority: int = 0
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    resolved_at: datetime | None = None


# ─── Analysis Models ────────────────────────────────────────


class ProjectAnalysis(BaseModel):
    """Result of the Orchestrator analyzing current project state.

    Contains a summary, metrics, and ranked task proposals.
    """

    id: str = Field(default_factory=lambda: f"analysis-{uuid.uuid4().hex[:8]}")
    total_tasks_completed: int = 0
    total_tasks_failed: int = 0
    velocity_tasks_per_hour: float = 0.0
    focus_area: str = ""
    summary: str = ""
    proposals: list[TaskProposal] = Field(default_factory=list)
    status: str = "ok"
    timestamp: datetime = Field(default_factory=lambda: datetime.now(UTC))


# ─── Metrics Models ─────────────────────────────────────────


class MetricsSnapshot(BaseModel):
    """Point-in-time metrics for a SuperWork session."""

    tasks_completed: int = 0
    tasks_failed: int = 0
    tokens_used: int = 0
    cost_usd: float = 0.0
    velocity_tasks_per_hour: float = 0.0
    success_rate: float = 1.0
    session_duration_seconds: int = 0
    timestamp: datetime = Field(default_factory=lambda: datetime.now(UTC))


class PredictionResult(BaseModel):
    """ETA and cost prediction based on current velocity."""

    remaining_tasks: int = 0
    estimated_hours: float = 0.0
    estimated_cost_usd: float = 0.0
    estimated_completion: datetime | None = None
    confidence: float = Field(0.5, ge=0.0, le=1.0)


# ─── Session Model ──────────────────────────────────────────


class SuperWorkSession(BaseModel):
    """State of a running SuperWork supervisor session."""

    id: str = Field(default_factory=lambda: f"sw-{uuid.uuid4().hex[:8]}")
    project_path: str
    status: SessionStatus = SessionStatus.INITIALIZING
    started_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    stopped_at: datetime | None = None
    metrics: MetricsSnapshot = Field(default_factory=MetricsSnapshot)
    active_proposals: list[TaskProposal] = Field(default_factory=list)
